--------------------------------------------------------
--  파일이 생성됨 - 화요일-10월-28-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADDRESS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."ADDRESS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 24 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence BOARD_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."BOARD_ID_SEQ"  MINVALUE 0 MAXVALUE 999 INCREMENT BY 1 START WITH 40 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence CATEGORIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."CATEGORIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence DEFECT_REPORTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."DEFECT_REPORTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence INQUIRIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."INQUIRIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 87 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence ITEM_IMAGES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."ITEM_IMAGES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence MYCART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."MYCART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence NOTICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."NOTICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 6 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence ORDERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."ORDERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 43 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence REPLIES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."REPLIES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence REVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GAGI"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table ACCOUNT_TRANSFERS
--------------------------------------------------------

  CREATE TABLE "GAGI"."ACCOUNT_TRANSFERS" 
   (	"ID" NUMBER, 
	"ORDER_ID" NUMBER NOT NULL ENABLE, 
	"BUYER_ID" NUMBER NOT NULL ENABLE, 
	"SELLER_ID" NUMBER NOT NULL ENABLE, 
	"AMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
	"DEPOSITOR_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DEPOSIT_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DEPOSIT_BANK" VARCHAR2(50), 
	"DEPOSIT_MEMO" VARCHAR2(100), 
	"SELLER_BANK" VARCHAR2(50) NOT NULL ENABLE, 
	"SELLER_ACCOUNT" VARCHAR2(50) NOT NULL ENABLE, 
	"SELLER_ACCOUNT_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(30) DEFAULT 'awaiting_deposit' NOT NULL ENABLE, 
	"CONFIRMED_BY" NUMBER, 
	"CONFIRMED_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_AT_BUYER" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_AT_SELLER" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_AT_CONFIRMER" FOREIGN KEY ("CONFIRMED_BY")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."ID" IS '이체 ID'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."ORDER_ID" IS '주문 번호 (1:1 매칭)'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."BUYER_ID" IS '구매자 (FK)'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."SELLER_ID" IS '판매자 (FK)'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."AMOUNT" IS '거래 금액'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."DEPOSITOR_NAME" IS '실제 입금자명'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."DEPOSIT_DATE" IS '입금일'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."DEPOSIT_BANK" IS '입금 은행'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."DEPOSIT_MEMO" IS '입금 메모'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."SELLER_BANK" IS '판매자 은행'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."SELLER_ACCOUNT" IS '판매자 계좌'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."SELLER_ACCOUNT_NAME" IS '판매자 예금주명'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."STATUS" IS '상태'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."CONFIRMED_BY" IS '입금 확인자'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."CONFIRMED_AT" IS '확인 시각'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."ACCOUNT_TRANSFERS"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."ACCOUNT_TRANSFERS"  IS '입출금/정산 기록'
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "GAGI"."ADDRESS" 
   (	"ADDRESS_ID" NUMBER NOT NULL ENABLE, 
	"ZIP_CODE" VARCHAR2(5) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(200) NOT NULL ENABLE, 
	"ADDRESS_DETAIL" VARCHAR2(50), 
	"IS_DEFAULT" CHAR(1) DEFAULT 'N', 
	"USER_ID" NUMBER, 
	"DELEVERY_NAME" VARCHAR2(10) NOT NULL ENABLE, 
	"DELEVERY_PICKUP" VARCHAR2(10), 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ADDRESS_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."ADDRESS"."ADDRESS_ID" IS '주소번호'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."ZIP_CODE" IS '우편번호'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."ADDRESS" IS '주소'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."ADDRESS_DETAIL" IS '상세주소'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."IS_DEFAULT" IS '기본배송지여부'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."DELEVERY_NAME" IS '수령자명'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."DELEVERY_PICKUP" IS '수령지'
   COMMENT ON COLUMN "GAGI"."ADDRESS"."PHONE" IS '전화번호'
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "GAGI"."CATEGORIES" 
   (	"CATEGORY_ID" NUMBER, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"CREATED_DT" TIMESTAMP (6) DEFAULT CURRENT_DATE, 
	"UPDATED_DT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."CATEGORIES"."CATEGORY_ID" IS '카테고리 번호'
   COMMENT ON COLUMN "GAGI"."CATEGORIES"."NAME" IS '카테고리 이름'
   COMMENT ON COLUMN "GAGI"."CATEGORIES"."CREATED_DT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."CATEGORIES"."UPDATED_DT" IS '수정일'
--------------------------------------------------------
--  DDL for Table CHAT_MESSAGES
--------------------------------------------------------

  CREATE TABLE "GAGI"."CHAT_MESSAGES" 
   (	"ID" NUMBER, 
	"ROOM_ID" NUMBER NOT NULL ENABLE, 
	"SENDER_ID" NUMBER NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(2000) NOT NULL ENABLE, 
	"SENT_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"READ_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_CM_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "GAGI"."CHAT_ROOMS" ("ID") ENABLE, 
	 CONSTRAINT "FK_CM_SENDER" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."ID" IS '메시지 ID'
   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."ROOM_ID" IS '채팅방 ID (FK)'
   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."SENDER_ID" IS '발신자 ID (FK)'
   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."MESSAGE" IS '메시지 내용'
   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."SENT_AT" IS '전송 시각'
   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."READ_AT" IS '읽은 시각'
   COMMENT ON COLUMN "GAGI"."CHAT_MESSAGES"."CREATED_AT" IS '생성일'
   COMMENT ON TABLE "GAGI"."CHAT_MESSAGES"  IS '채팅 메시지'
--------------------------------------------------------
--  DDL for Table CHAT_PARTICIPANTS
--------------------------------------------------------

  CREATE TABLE "GAGI"."CHAT_PARTICIPANTS" 
   (	"ID" NUMBER, 
	"ROOM_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"JOINED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"LAST_READ_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_CP_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "GAGI"."CHAT_ROOMS" ("ID") ENABLE, 
	 CONSTRAINT "FK_CP_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."ID" IS '참여 ID'
   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."ROOM_ID" IS '채팅방 ID (FK)'
   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."USER_ID" IS '회원 ID (FK)'
   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."JOINED_AT" IS '참여일'
   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."LAST_READ_AT" IS '마지막 읽은 시각'
   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."CHAT_PARTICIPANTS"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."CHAT_PARTICIPANTS"  IS '채팅방 참여자'
--------------------------------------------------------
--  DDL for Table CHAT_ROOMS
--------------------------------------------------------

  CREATE TABLE "GAGI"."CHAT_ROOMS" 
   (	"ID" NUMBER, 
	"ITEM_ID" NUMBER, 
	"CREATOR_USER_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_CR_USER" FOREIGN KEY ("CREATOR_USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_CR_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."CHAT_ROOMS"."ID" IS '채팅방 ID'
   COMMENT ON COLUMN "GAGI"."CHAT_ROOMS"."ITEM_ID" IS '상품 ID (FK)'
   COMMENT ON COLUMN "GAGI"."CHAT_ROOMS"."CREATOR_USER_ID" IS '방 생성자 (FK)'
   COMMENT ON COLUMN "GAGI"."CHAT_ROOMS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."CHAT_ROOMS"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."CHAT_ROOMS"  IS '채팅방'
--------------------------------------------------------
--  DDL for Table INQUIRIES
--------------------------------------------------------

  CREATE TABLE "GAGI"."INQUIRIES" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"RESPONDER_ID" NUMBER, 
	"CATEGORY" VARCHAR2(50), 
	"SUBJECT" VARCHAR2(200) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(2000) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) DEFAULT 'open' NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"RESPONDED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_INQ_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_INQ_RESP" FOREIGN KEY ("RESPONDER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."INQUIRIES"."ID" IS '문의 ID'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."USER_ID" IS '문의자 (FK)'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."RESPONDER_ID" IS '응답자 (관리자, FK)'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."CATEGORY" IS '문의 카테고리'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."SUBJECT" IS '제목'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."MESSAGE" IS '내용'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."STATUS" IS '상태(open, closed 등)'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."RESPONDED_AT" IS '응답일'
   COMMENT ON COLUMN "GAGI"."INQUIRIES"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."INQUIRIES"  IS '1:1 문의'
--------------------------------------------------------
--  DDL for Table ITEMS
--------------------------------------------------------

  CREATE TABLE "GAGI"."ITEMS" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER, 
	"TITLE" VARCHAR2(200) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(2000), 
	"DELIVERY" VARCHAR2(200), 
	"IS_DIRECT_DEAL" CHAR(1) DEFAULT 'N', 
	"PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"AMOUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"BANK_ACCOUNT_NUMBER" VARCHAR2(50), 
	"SALES_STATUS" VARCHAR2(20) DEFAULT 'available' NOT NULL ENABLE, 
	"VIEWS" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"DELETED_AT" TIMESTAMP (6), 
	"IS_DELETE" CHAR(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PK_ITEMS_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ITEMS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_ITEMS_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "GAGI"."CATEGORIES" ("CATEGORY_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."ITEMS"."ID" IS '상품 번호'
   COMMENT ON COLUMN "GAGI"."ITEMS"."USER_ID" IS '등록한 회원 번호 (FK)'
   COMMENT ON COLUMN "GAGI"."ITEMS"."CATEGORY_ID" IS '카테고리 번호 (FK)'
   COMMENT ON COLUMN "GAGI"."ITEMS"."TITLE" IS '상품 제목'
   COMMENT ON COLUMN "GAGI"."ITEMS"."DESCRIPTION" IS '상품 설명'
   COMMENT ON COLUMN "GAGI"."ITEMS"."DELIVERY" IS '거래 지역/주소'
   COMMENT ON COLUMN "GAGI"."ITEMS"."IS_DIRECT_DEAL" IS '직거래 가능 여부 (Y/N)'
   COMMENT ON COLUMN "GAGI"."ITEMS"."PRICE" IS '판매 가격'
   COMMENT ON COLUMN "GAGI"."ITEMS"."AMOUNT" IS '수량'
   COMMENT ON COLUMN "GAGI"."ITEMS"."BANK_ACCOUNT_NUMBER" IS '판매자 계좌번호'
   COMMENT ON COLUMN "GAGI"."ITEMS"."SALES_STATUS" IS '판매 상태'
   COMMENT ON COLUMN "GAGI"."ITEMS"."VIEWS" IS '조회수'
   COMMENT ON COLUMN "GAGI"."ITEMS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."ITEMS"."UPDATED_AT" IS '수정일'
   COMMENT ON COLUMN "GAGI"."ITEMS"."DELETED_AT" IS '삭제일 (soft delete)'
   COMMENT ON COLUMN "GAGI"."ITEMS"."IS_DELETE" IS '삭제여부'
   COMMENT ON TABLE "GAGI"."ITEMS"  IS '상품 정보 테이블'
--------------------------------------------------------
--  DDL for Table ITEM_IMAGES
--------------------------------------------------------

  CREATE TABLE "GAGI"."ITEM_IMAGES" 
   (	"ID" NUMBER, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"IMAGE_URL" VARCHAR2(500), 
	"SORT_ORDER" NUMBER DEFAULT 0, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"FILENAME" VARCHAR2(256) NOT NULL ENABLE, 
	"UUID" VARCHAR2(100), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ITEM_IMG" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."ID" IS '이미지 ID'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."ITEM_ID" IS '상품 ID (FK)'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."IMAGE_URL" IS '이미지 경로'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."SORT_ORDER" IS '정렬 순서'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."UPDATED_AT" IS '수정일'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."FILENAME" IS '파일명'
   COMMENT ON COLUMN "GAGI"."ITEM_IMAGES"."UUID" IS 'UUID'
   COMMENT ON TABLE "GAGI"."ITEM_IMAGES"  IS '상품 이미지'
--------------------------------------------------------
--  DDL for Table MYCART
--------------------------------------------------------

  CREATE TABLE "GAGI"."MYCART" 
   (	"ID" NUMBER, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_CART_USER_ITEM" UNIQUE ("USER_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_CART_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_CART_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table NOTICES
--------------------------------------------------------

  CREATE TABLE "GAGI"."NOTICES" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(200) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(2000) NOT NULL ENABLE, 
	"VISIBLE" CHAR(1) DEFAULT 'Y', 
	"POSTED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"EXPIRES_AT" TIMESTAMP (6), 
	"ADMIN_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."NOTICES"."ID" IS '공지 ID'
   COMMENT ON COLUMN "GAGI"."NOTICES"."TITLE" IS '제목'
   COMMENT ON COLUMN "GAGI"."NOTICES"."CONTENT" IS '내용'
   COMMENT ON COLUMN "GAGI"."NOTICES"."VISIBLE" IS '노출 여부'
   COMMENT ON COLUMN "GAGI"."NOTICES"."POSTED_AT" IS '게시일'
   COMMENT ON COLUMN "GAGI"."NOTICES"."EXPIRES_AT" IS '만료일'
   COMMENT ON COLUMN "GAGI"."NOTICES"."ADMIN_ID" IS '작성자 (FK)'
   COMMENT ON COLUMN "GAGI"."NOTICES"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."NOTICES"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."NOTICES"  IS '공지사항'
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "GAGI"."ORDERS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER, 
	"PRICE" NUMBER(10,2), 
	"AMOUNT" NUMBER, 
	"TOTAL_PRICE" NUMBER(10,2) NOT NULL ENABLE, 
	"TRANSACTION_TYPE" VARCHAR2(20) DEFAULT '배송' NOT NULL ENABLE, 
	"PAYMENT_METHOD" VARCHAR2(50), 
	"RECIPIENT_NAME" VARCHAR2(100), 
	"RECIPIENT_PHONE" VARCHAR2(20), 
	"DELIVERY_ZIPCODE" VARCHAR2(20), 
	"DELIVERY_ADDRESS_MAIN" VARCHAR2(255), 
	"DELIVERY_ADDRESS_DETAIL" VARCHAR2(255), 
	"DELIVERY_MEMO" VARCHAR2(500), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ORDER_STATUS" VARCHAR2(20), 
	 CONSTRAINT "PK_ORDERS_NEW" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ITEM_ORDER" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."ORDERS"."ID" IS '주문PK'
   COMMENT ON COLUMN "GAGI"."ORDERS"."USER_ID" IS '주문자 (FK)'
   COMMENT ON COLUMN "GAGI"."ORDERS"."ITEM_ID" IS '상품 ID (FK)'
   COMMENT ON COLUMN "GAGI"."ORDERS"."PRICE" IS '상품 단가'
   COMMENT ON COLUMN "GAGI"."ORDERS"."AMOUNT" IS '주문 수량'
   COMMENT ON COLUMN "GAGI"."ORDERS"."TOTAL_PRICE" IS '총 주문 금액'
   COMMENT ON COLUMN "GAGI"."ORDERS"."TRANSACTION_TYPE" IS '거래유형 (배송/직거래)'
   COMMENT ON COLUMN "GAGI"."ORDERS"."PAYMENT_METHOD" IS '결제 수단'
   COMMENT ON COLUMN "GAGI"."ORDERS"."RECIPIENT_NAME" IS '수령인 이름'
   COMMENT ON COLUMN "GAGI"."ORDERS"."RECIPIENT_PHONE" IS '수령인 연락처'
   COMMENT ON COLUMN "GAGI"."ORDERS"."DELIVERY_ZIPCODE" IS '배송지 우편번호'
   COMMENT ON COLUMN "GAGI"."ORDERS"."DELIVERY_ADDRESS_MAIN" IS '배송지 주소(기본)'
   COMMENT ON COLUMN "GAGI"."ORDERS"."DELIVERY_ADDRESS_DETAIL" IS '배송지 주소(상세)'
   COMMENT ON COLUMN "GAGI"."ORDERS"."DELIVERY_MEMO" IS '배송 요청사항'
   COMMENT ON COLUMN "GAGI"."ORDERS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."ORDERS"."UPDATED_AT" IS '수정일'
   COMMENT ON COLUMN "GAGI"."ORDERS"."ORDER_STATUS" IS '주문 상태/입금준비,입금완료..취소'
--------------------------------------------------------
--  DDL for Table REPLIES
--------------------------------------------------------

  CREATE TABLE "GAGI"."REPLIES" 
   (	"REPLY_ID" NUMBER, 
	"BOARD_TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"POST_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(1000) NOT NULL ENABLE, 
	"CREATED_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_AT" DATE, 
	 PRIMARY KEY ("REPLY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_REPLIES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."REPLIES"."REPLY_ID" IS '댓글 PK'
   COMMENT ON COLUMN "GAGI"."REPLIES"."BOARD_TYPE" IS '게시판 구분'
   COMMENT ON COLUMN "GAGI"."REPLIES"."POST_ID" IS '원본 글 ID'
   COMMENT ON COLUMN "GAGI"."REPLIES"."USER_ID" IS 'USERS.ID FK'
   COMMENT ON COLUMN "GAGI"."REPLIES"."CONTENT" IS '댓글 내용'
--------------------------------------------------------
--  DDL for Table REPORTS
--------------------------------------------------------

  CREATE TABLE "GAGI"."REPORTS" 
   (	"DEFECT_ID" NUMBER NOT NULL ENABLE, 
	"ORDER_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER, 
	"DEFECT_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000), 
	"IMAGE_URL" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) DEFAULT 'PENDING' NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."REPORTS"."DEFECT_ID" IS '신고ID'
   COMMENT ON COLUMN "GAGI"."REPORTS"."ORDER_ITEM_ID" IS '주문상품 ID (FK: ORDER_ITEMS.ID)'
   COMMENT ON COLUMN "GAGI"."REPORTS"."USER_ID" IS '신고자 회원 ID (FK: USERS.ID)'
   COMMENT ON COLUMN "GAGI"."REPORTS"."PRODUCT_ID" IS '상품 ID (FK: PRODUCTS.ID)'
   COMMENT ON COLUMN "GAGI"."REPORTS"."DEFECT_TYPE" IS '불량 유형 (예: 파손, 오염, 오배송 등)'
   COMMENT ON COLUMN "GAGI"."REPORTS"."DESCRIPTION" IS '상세설명'
   COMMENT ON COLUMN "GAGI"."REPORTS"."IMAGE_URL" IS '불량 증빙 이미지 경로'
   COMMENT ON COLUMN "GAGI"."REPORTS"."STATUS" IS '신고 진행 상태 (PENDING=접수, IN_PROGRESS=처리중, RESOLVED=해결, REJECTED=반려)'
   COMMENT ON COLUMN "GAGI"."REPORTS"."CREATED_AT" IS '최초 신고 시간'
   COMMENT ON COLUMN "GAGI"."REPORTS"."UPDATED_AT" IS '신고 상태 변경 시간'
--------------------------------------------------------
--  DDL for Table REVIEWS
--------------------------------------------------------

  CREATE TABLE "GAGI"."REVIEWS" 
   (	"ID" NUMBER, 
	"ORDER_ITEM_ID" NUMBER NOT NULL ENABLE, 
	"REVIEWER_ID" NUMBER NOT NULL ENABLE, 
	"TARGET_ID" NUMBER NOT NULL ENABLE, 
	"RATING_NUMBER" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE, 
	"COMMENT_TEXT" VARCHAR2(1000), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 UNIQUE ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_REV_REVIEWER" FOREIGN KEY ("REVIEWER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_REV_TARGET" FOREIGN KEY ("TARGET_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."REVIEWS"."ID" IS '리뷰 ID'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."ORDER_ITEM_ID" IS '주문 상세 ID (FK, 리뷰 1:1)'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."REVIEWER_ID" IS '작성자 (FK)'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."TARGET_ID" IS '대상(판매자/구매자, FK)'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."RATING_NUMBER" IS '평점'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."COMMENT_TEXT" IS '리뷰 내용'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."REVIEWS"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."REVIEWS"  IS '리뷰'
--------------------------------------------------------
--  DDL for Table SELECTLIST
--------------------------------------------------------

  CREATE TABLE "GAGI"."SELECTLIST" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"QUANTITY" NUMBER, 
	"ADDED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_SL_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE, 
	 CONSTRAINT "FK_SL_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."SELECTLIST"."ID" IS '선택 번호'
   COMMENT ON COLUMN "GAGI"."SELECTLIST"."TYPE" IS '타입(cart/wishlist)'
   COMMENT ON COLUMN "GAGI"."SELECTLIST"."USER_ID" IS '회원 ID (FK)'
   COMMENT ON COLUMN "GAGI"."SELECTLIST"."ITEM_ID" IS '상품 ID (FK)'
   COMMENT ON COLUMN "GAGI"."SELECTLIST"."QUANTITY" IS '수량'
   COMMENT ON COLUMN "GAGI"."SELECTLIST"."ADDED_AT" IS '등록일'
   COMMENT ON COLUMN "GAGI"."SELECTLIST"."UPDATED_AT" IS '수정일'
   COMMENT ON TABLE "GAGI"."SELECTLIST"  IS '장바구니/찜 목록'
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "GAGI"."USERS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(255), 
	"PHONE" VARCHAR2(20), 
	"USER_TYPE" VARCHAR2(20) DEFAULT 'buyer' NOT NULL ENABLE, 
	"LOGIN_TYPE" VARCHAR2(20) DEFAULT 'local' NOT NULL ENABLE, 
	"PROVIDER_ID" VARCHAR2(255), 
	"PROFILE_IMAGE" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) DEFAULT 'active', 
	"CREATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"NICKNAME" VARCHAR2(20), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_USERS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_USERS_PHONE" UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "UK_USERS_PROVIDER" UNIQUE ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "GAGI"."USERS"."ID" IS '회원 번호 (PK)'
   COMMENT ON COLUMN "GAGI"."USERS"."USERNAME" IS '이름'
   COMMENT ON COLUMN "GAGI"."USERS"."EMAIL" IS '이메일 (고유)'
   COMMENT ON COLUMN "GAGI"."USERS"."PASSWORD" IS '비밀번호 (소셜 로그인 시 NULL 가능)'
   COMMENT ON COLUMN "GAGI"."USERS"."PHONE" IS '전화번호'
   COMMENT ON COLUMN "GAGI"."USERS"."USER_TYPE" IS '회원 유형 (구매자/판매자/관리자)'
   COMMENT ON COLUMN "GAGI"."USERS"."LOGIN_TYPE" IS '로그인 유형 (로컬/소셜)'
   COMMENT ON COLUMN "GAGI"."USERS"."PROVIDER_ID" IS '소셜 계정 고유 ID'
   COMMENT ON COLUMN "GAGI"."USERS"."PROFILE_IMAGE" IS '프로필 이미지 경로'
   COMMENT ON COLUMN "GAGI"."USERS"."STATUS" IS '계정 상태 (active, suspended 등)'
   COMMENT ON COLUMN "GAGI"."USERS"."CREATED_AT" IS '생성일'
   COMMENT ON COLUMN "GAGI"."USERS"."UPDATED_AT" IS '수정일'
   COMMENT ON COLUMN "GAGI"."USERS"."NICKNAME" IS '닉네임'
   COMMENT ON TABLE "GAGI"."USERS"  IS '회원 정보 테이블'
--------------------------------------------------------
--  DDL for Index PK_ORDERS_NEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."PK_ORDERS_NEW" ON "GAGI"."ORDERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UK_USERS_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."UK_USERS_USERNAME" ON "GAGI"."USERS" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UK_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."UK_USERS_EMAIL" ON "GAGI"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."ADDRESS_PK" ON "GAGI"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UK_CART_USER_ITEM
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."UK_CART_USER_ITEM" ON "GAGI"."MYCART" ("USER_ID", "ITEM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UK_USERS_PHONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."UK_USERS_PHONE" ON "GAGI"."USERS" ("PHONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index UK_USERS_PROVIDER
--------------------------------------------------------

  CREATE UNIQUE INDEX "GAGI"."UK_USERS_PROVIDER" ON "GAGI"."USERS" ("PROVIDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Trigger MYCART_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GAGI"."MYCART_TRG" 
BEFORE INSERT ON MYCART
FOR EACH ROW
BEGIN
    :NEW.ID := MYCART_SEQ.NEXTVAL;
END;

ALTER TRIGGER "GAGI"."MYCART_TRG" ENABLE
--------------------------------------------------------
--  Constraints for Table REPLIES
--------------------------------------------------------

  ALTER TABLE "GAGI"."REPLIES" ADD PRIMARY KEY ("REPLY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."REPLIES" MODIFY ("CREATED_AT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPLIES" MODIFY ("CONTENT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPLIES" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPLIES" MODIFY ("POST_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPLIES" MODIFY ("BOARD_TYPE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ITEM_IMAGES
--------------------------------------------------------

  ALTER TABLE "GAGI"."ITEM_IMAGES" MODIFY ("FILENAME" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ITEM_IMAGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."ITEM_IMAGES" MODIFY ("ITEM_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "GAGI"."REVIEWS" ADD UNIQUE ("ORDER_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."REVIEWS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."REVIEWS" MODIFY ("RATING_NUMBER" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REVIEWS" MODIFY ("TARGET_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REVIEWS" MODIFY ("REVIEWER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REVIEWS" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ACCOUNT_TRANSFERS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" ADD UNIQUE ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("SELLER_ACCOUNT_NAME" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("SELLER_ACCOUNT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("SELLER_BANK" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("DEPOSIT_DATE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("DEPOSITOR_NAME" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("AMOUNT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("SELLER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("BUYER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" MODIFY ("ORDER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table MYCART
--------------------------------------------------------

  ALTER TABLE "GAGI"."MYCART" ADD CONSTRAINT "UK_CART_USER_ITEM" UNIQUE ("USER_ID", "ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."MYCART" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."MYCART" MODIFY ("QUANTITY" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."MYCART" MODIFY ("ITEM_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."MYCART" MODIFY ("USER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ORDERS" ADD CONSTRAINT "PK_ORDERS_NEW" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."ORDERS" MODIFY ("TRANSACTION_TYPE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ORDERS" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ORDERS" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ORDERS" MODIFY ("ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table NOTICES
--------------------------------------------------------

  ALTER TABLE "GAGI"."NOTICES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."NOTICES" MODIFY ("CONTENT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."NOTICES" MODIFY ("TITLE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "GAGI"."CHAT_ROOMS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "GAGI"."USERS" ADD CONSTRAINT "UK_USERS_PROVIDER" UNIQUE ("PROVIDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."USERS" ADD CONSTRAINT "UK_USERS_PHONE" UNIQUE ("PHONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."USERS" ADD CONSTRAINT "UK_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."USERS" ADD CONSTRAINT "UK_USERS_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."USERS" MODIFY ("LOGIN_TYPE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."USERS" MODIFY ("USER_TYPE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."USERS" MODIFY ("USERNAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table REPORTS
--------------------------------------------------------

  ALTER TABLE "GAGI"."REPORTS" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPORTS" MODIFY ("DEFECT_TYPE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPORTS" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPORTS" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."REPORTS" MODIFY ("DEFECT_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ITEMS" ADD CONSTRAINT "PK_ITEMS_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."ITEMS" MODIFY ("SALES_STATUS" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ITEMS" MODIFY ("AMOUNT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ITEMS" MODIFY ("PRICE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ITEMS" MODIFY ("TITLE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ITEMS" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ITEMS" MODIFY ("IS_DELETE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "GAGI"."CATEGORIES" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."CATEGORIES" MODIFY ("NAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table INQUIRIES
--------------------------------------------------------

  ALTER TABLE "GAGI"."INQUIRIES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."INQUIRIES" MODIFY ("STATUS" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."INQUIRIES" MODIFY ("MESSAGE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."INQUIRIES" MODIFY ("SUBJECT" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."INQUIRIES" MODIFY ("USER_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "GAGI"."CHAT_MESSAGES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."CHAT_MESSAGES" MODIFY ("MESSAGE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."CHAT_MESSAGES" MODIFY ("SENDER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."CHAT_MESSAGES" MODIFY ("ROOM_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ADDRESS" MODIFY ("PHONE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ADDRESS" MODIFY ("DELEVERY_NAME" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ADDRESS" MODIFY ("ADDRESS" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."ADDRESS" MODIFY ("ZIP_CODE" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table CHAT_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "GAGI"."CHAT_PARTICIPANTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."CHAT_PARTICIPANTS" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."CHAT_PARTICIPANTS" MODIFY ("ROOM_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SELECTLIST
--------------------------------------------------------

  ALTER TABLE "GAGI"."SELECTLIST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "GAGI"."SELECTLIST" MODIFY ("ITEM_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."SELECTLIST" MODIFY ("USER_ID" NOT NULL ENABLE)
  ALTER TABLE "GAGI"."SELECTLIST" MODIFY ("TYPE" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT_TRANSFERS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" ADD CONSTRAINT "FK_AT_BUYER" FOREIGN KEY ("BUYER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" ADD CONSTRAINT "FK_AT_CONFIRMER" FOREIGN KEY ("CONFIRMED_BY")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
  ALTER TABLE "GAGI"."ACCOUNT_TRANSFERS" ADD CONSTRAINT "FK_AT_SELLER" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ADDRESS" ADD CONSTRAINT "ADDRESS_ID" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CHAT_MESSAGES
--------------------------------------------------------

  ALTER TABLE "GAGI"."CHAT_MESSAGES" ADD CONSTRAINT "FK_CM_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "GAGI"."CHAT_ROOMS" ("ID") ENABLE
  ALTER TABLE "GAGI"."CHAT_MESSAGES" ADD CONSTRAINT "FK_CM_SENDER" FOREIGN KEY ("SENDER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CHAT_PARTICIPANTS
--------------------------------------------------------

  ALTER TABLE "GAGI"."CHAT_PARTICIPANTS" ADD CONSTRAINT "FK_CP_ROOM" FOREIGN KEY ("ROOM_ID")
	  REFERENCES "GAGI"."CHAT_ROOMS" ("ID") ENABLE
  ALTER TABLE "GAGI"."CHAT_PARTICIPANTS" ADD CONSTRAINT "FK_CP_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table CHAT_ROOMS
--------------------------------------------------------

  ALTER TABLE "GAGI"."CHAT_ROOMS" ADD CONSTRAINT "FK_CR_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
  ALTER TABLE "GAGI"."CHAT_ROOMS" ADD CONSTRAINT "FK_CR_USER" FOREIGN KEY ("CREATOR_USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table INQUIRIES
--------------------------------------------------------

  ALTER TABLE "GAGI"."INQUIRIES" ADD CONSTRAINT "FK_INQ_RESP" FOREIGN KEY ("RESPONDER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
  ALTER TABLE "GAGI"."INQUIRIES" ADD CONSTRAINT "FK_INQ_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ITEMS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ITEMS" ADD CONSTRAINT "FK_ITEMS_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "GAGI"."CATEGORIES" ("CATEGORY_ID") ENABLE
  ALTER TABLE "GAGI"."ITEMS" ADD CONSTRAINT "FK_ITEMS_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ITEM_IMAGES
--------------------------------------------------------

  ALTER TABLE "GAGI"."ITEM_IMAGES" ADD CONSTRAINT "FK_ITEM_IMG" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
--------------------------------------------------------
--  Ref Constraints for Table MYCART
--------------------------------------------------------

  ALTER TABLE "GAGI"."MYCART" ADD CONSTRAINT "FK_CART_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
  ALTER TABLE "GAGI"."MYCART" ADD CONSTRAINT "FK_CART_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "GAGI"."ORDERS" ADD CONSTRAINT "FK_ITEM_ORDER" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
--------------------------------------------------------
--  Ref Constraints for Table REPLIES
--------------------------------------------------------

  ALTER TABLE "GAGI"."REPLIES" ADD CONSTRAINT "FK_REPLIES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table REVIEWS
--------------------------------------------------------

  ALTER TABLE "GAGI"."REVIEWS" ADD CONSTRAINT "FK_REV_REVIEWER" FOREIGN KEY ("REVIEWER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
  ALTER TABLE "GAGI"."REVIEWS" ADD CONSTRAINT "FK_REV_TARGET" FOREIGN KEY ("TARGET_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SELECTLIST
--------------------------------------------------------

  ALTER TABLE "GAGI"."SELECTLIST" ADD CONSTRAINT "FK_SL_ITEM" FOREIGN KEY ("ITEM_ID")
	  REFERENCES "GAGI"."ITEMS" ("ID") ON DELETE CASCADE ENABLE
  ALTER TABLE "GAGI"."SELECTLIST" ADD CONSTRAINT "FK_SL_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "GAGI"."USERS" ("ID") ENABLE
